<?php
// Plugin definition
$plugin = array(
  'title' => t('B2B Leaders Landing'),
  'icon' => 'b2b-leaders-landing.png',
  'category' => t('B2B Marketing'),
  'theme' => 'b2b-leaders-landing',
  'regions' => array(
    'header' => t('Header'),
    'column1' => t('First Column'),
    'column2' => t('Second Column'),
    'column3' => t('Third Column'),
    'column4' => t('Fourth Column'),
    'middle' => t('Middle'),
    'middle1' => t('Middle 1'),
    'middle2' => t('Middle 2'),
    'middle3' => t('Middle 3'),
    'middle4' => t('Middle 4'),
    'middle5' => t('Middle 5'),
    'footer' => t('Footer'),
    'logos' => t('Logos'),
  ),
);
