<?php
// Plugin definition
$plugin = array(
  'title' => t('b2b-training-landing'),
  'icon' => 'b2b-training-landing.png',
  'category' => t('B2B Marketing'),
  'theme' => 'b2b-training-landing',
  'admin css' => '../../../stylesheets/foundation-grid.css',
  'regions' => array(
    'header' => t('Header'),
    'header-title' => t('Header Title'),
    'training-modules' => t('Training modules'),
    'certificates' => t('Certificates'),
    'certificates2' => t('Certificates 2'),
    'certificates-courses' => t('Certificates courses'),
    'certificates-courses2' => t('Certificates courses 2'),
    'bottom-paragraphs' => t('Bottom paragraphs'),
    'team-solutions' => t('Team solutions'),
    'skills-audits' => t('Skills audits'),
    'testimonials' => t('Testimonials'),
    'logos' => t('Logos'),
  ),
);

