<?php
// Plugin definition
$plugin = array(
  'title' => t('B2B Two Column Flipped'),
  'icon' => 'b2b-2col-flipped.png',
  'category' => t('B2B Marketing'),
  'theme' => 'b2b-2col-flipped',
  'css' => 'b2b-2col-flipped.css',
  'regions' => array(
  'sidebar' => t('Sidebar'),
  'contentmain' => t('Content'),
  'breadcrumbs-full' => t('Full Width Breadcrumbs'),
  'related-content' => t('Related Content'),
  'comments' => t('Comments'),
  ),
);
