<?php
// Plugin definition
$plugin = array(
  'title' => t('Topics'),
  'icon' => 'b2b-topics.png',
  'category' => t('B2B Marketing'),
  'theme' => 'b2b-topics',
  'css' => 'b2b-topics.css',
  'admin css' => '../../../stylesheets/foundation-grid.css',
  'regions' => array(
    'top' => t('Top'),
    'sponsor-feature' => t('Sponsor feature'),
    'panel-1-1' => t('1-1'),
    'panel-1-2' => t('1-2'),
    'panel-2-1' => t('2-1'),
    'panel-2-2' => t('2-2'),
    'sponsor' => t('Sponsor'),
    'panel-3-1' => t('3-1'),
    'panel-4-1' => t('4-1'),
    'panel-4-2' => t('4-2'),
    'panel-5-1' => t('5-1'),
    'panel-6-1' => t('6-1'),
    'panel-6-2' => t('6-2'),
    'panel-6-3' => t('6-3'),
    'panel-7-1' => t('7-1'),
    'panel-7-2' => t('7-2'),
    'bottom' => t('Bottom'),
  ),
);
