<?php
// Plugin definition
$plugin = array(
  'title' => t('b2b-basic-variant'),
  'icon' => 'b2b-basic-variant.png',
  'category' => t('B2B Marketing'),
  'theme' => 'b2b-basic-variant',
  'admin css' => '../../../stylesheets/foundation-grid.css',
  'regions' => array(
    'hero' => t('Banner'),
    'top' => t('Top'),
    'panel-1-1' => t('1-1'),
    'panel-1-2' => t('1-2'),
  ),
);

